== Conventions in this repository

As a good software engineer, you avoid work where you can. Certainly if it is repetitious. You computer does a much better job at that.
You can even minimize configuration labor when you
sticking some to conventions a use it as in 'convention over configuration'.

The conventions we use are:

* The output format is always pdf.
* For every separate target document (pdf-file) there is a separate project, which is contained in a directory of its own.
* The document that is given as tex-source command line parameter is called `main.tex`.
* This main.tex file defines the document type, and has a fixed content, which only varies by document-type, like *sebireport* for a report, *sebiarticle* for *arcticles* as *sebisheets* for sheets.
* The actual content is organised in a file called material, which `\input`s or `\include`s the files that make up the final content.

.main.tex file content
[source,tex-source]
----
\input{sebireport}
\begin{document}
\input{material}
\end{document}
----

.material.tex file content (typical)
[source,tex-source]
----
\input{frontmatter}
\input{summary}
\pagenumbering{arabic}
\input{introduction}
\include{chap1}
\include{chap1}
----

* Use `\include` only for chapters, because the way they are treated by LaTeX. For on, `\include` cannot be nested, second, an `\include` typically forces a page break.
* Use `input` or `\InputIfFile` for everything else and
* Use `\includegraphics[...]{...}` to include figures or tables made up in pdf. Note that only the following file formats are accepted by pdflatex: .png, .pdf and .jpg.
Any svg file needs to be converted to pdf first.
